#ifndef LIBBREAKPAD_GLOBAL_H
#define LIBBREAKPAD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBBREAKPAD_LIBRARY)
#  define LIBBREAKPADSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBBREAKPADSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBBREAKPAD_GLOBAL_H
